apiVersion: v2
name: app-mongodb
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "1.16.0"
dependencies:
  - name: mongodb
    version: 15.4.5
    repository: https://charts.bitnami.com/bitnami

